travis:
  secure:
    BINSTAR_TOKEN: Ku56koRweALxTuKsdtUcbjgm/3ALOyOWcRr7IOUDwq4HMd5bnAItFW75e0jqYyRFgaRIDrW85DafKRBzARE44BFJgZBskd0fG/qbLCoyj99tfFJ88lamdacVTkEBJxz1DX45tGOA+Vb+XdtKxAx78HJ8zvYpyhZ7xIEz+xmivrX9QyK/CydjoJ2djbhJizDlr/aexQNsOyzyGX8XFufHuFQA5UG1aBSZa6HWABQb1VJXEwQfYEbc/UrGzUToUnTcinQPQRF/z6PS8wOAh2vTnPDG8jjo1NaRWDVhOJHzbcUq+a/gLkiSX6jFV+AUSqh47A0cc3Q+iLLEs45yaCrgZKqFS5uPsbvGqF23UuirXJlQO+iQztE+jMu1IrtmlHxCl18KoqzhIOtKYhGYwXjIJu3nLkyDmGVUwdxmUQM9Su6Q2+SO6jSfs3UID9VNZ5/zPzX+FRHB+SmNCMqLvUFtczFiNBZocvlJPLM2XAJ1SrOToxoPt/ey0w7MP7Nh5ojiKCMPs5Lg1URjiIXFt9L0CfzB1XLLlWSUh9cH5C21ti86hRMA/Cb8EHmfGt5eMTohEDdxCJxyKLLlN6dVwMwy5OkbHZdxgEB2JzZGGF2LsYbs6vaB7ZeTgqy+aRdSaLdSvjP4i8gdfKiv8lg0e9DiGK1UzUaXqGKX7rJDzbPbX7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
